# Builds the logos-package-manager-ui library
{ pkgs, common, src, logosPackageManagerModule, logosSdk }:

pkgs.stdenv.mkDerivation {
  pname = "${common.pname}-lib";
  version = common.version;
  
  inherit src;
  inherit (common) buildInputs cmakeFlags meta env;
  
  # Add logosSdk to nativeBuildInputs for logos-cpp-generator
  nativeBuildInputs = common.nativeBuildInputs ++ [ logosSdk ];
  
  preConfigure = ''
    runHook prePreConfigure
    
    # Set macOS deployment target to match Qt frameworks
    export MACOSX_DEPLOYMENT_TARGET=12.0
    
    # Create generated_code directory for generated files
    mkdir -p ./generated_code
    
    # Copy include files from logos-package-manager-module result
    echo "Copying include files from logos-package-manager-module..."
    if [ -d "${logosPackageManagerModule}/include" ]; then
      echo "Found include directory in logos-package-manager-module"
      cp -r "${logosPackageManagerModule}/include"/* ./generated_code/
      echo "Copied include files:"
      ls -la ./generated_code/
    else
      echo "Warning: No include directory found in logos-package-manager-module"
    fi
    
    # Run logos-cpp-generator with metadata.json and --general-only flag
    echo "Running logos-cpp-generator..."
    logos-cpp-generator --metadata ${src}/metadata.json --general-only --output-dir ./generated_code
    
    # Check what was generated by logos-cpp-generator
    echo "Checking generated files in generated_code:"
    ls -la ./generated_code/
    
    # Don't move any files - keep everything in generated_code root for simplicity
    # The logos_sdk.h includes them with bare names like "core_manager_api.h"
    echo "Files in generated_code:"
    ls -la ./generated_code/
    
    # For nix builds, we don't need to create the logos-cpp-sdk/cpp/generated structure
    # since we're using the installed SDK layout and linking against the SDK library
    echo "Using installed SDK layout - generated files are for reference only"
    
    # Copy logos-cpp-sdk source files to expected location for CMakeLists.txt
    echo "Copying logos-cpp-sdk source files..."
    # Create the include/cpp structure that CMake expects
    echo "Creating include/cpp structure..."
    mkdir -p ./logos-cpp-sdk/include/cpp
    cp -r ${logosSdk}/include/cpp/* ./logos-cpp-sdk/include/cpp/
    echo "Files in logos-cpp-sdk/include/cpp/:"
    ls -la ./logos-cpp-sdk/include/cpp/
    
    # Also copy core headers to fix relative includes
    echo "Copying core headers..."
    mkdir -p ./logos-cpp-sdk/include/core
    cp -r ${logosSdk}/include/core/* ./logos-cpp-sdk/include/core/
    echo "Files in logos-cpp-sdk/include/core/:"
    ls -la ./logos-cpp-sdk/include/core/
    
    # Copy SDK library files to lib directory
    echo "Copying SDK library files..."
    mkdir -p ./logos-cpp-sdk/lib
    if [ -f "${logosSdk}/lib/liblogos_sdk.dylib" ]; then
      cp "${logosSdk}/lib/liblogos_sdk.dylib" ./logos-cpp-sdk/lib/
    elif [ -f "${logosSdk}/lib/liblogos_sdk.so" ]; then
      cp "${logosSdk}/lib/liblogos_sdk.so" ./logos-cpp-sdk/lib/
    elif [ -f "${logosSdk}/lib/liblogos_sdk.a" ]; then
      cp "${logosSdk}/lib/liblogos_sdk.a" ./logos-cpp-sdk/lib/
    fi
    
    runHook postPreConfigure
  '';
  
  configurePhase = ''
    runHook preConfigure
    
    echo "Configuring logos-package-manager-ui..."
    echo "logosSdk: ${logosSdk}"
    echo "logosLiblogos: ${toString common.env.LOGOS_LIBLOGOS_ROOT}"
    
    # Verify that the logosSdk exists
    test -d "${logosSdk}" || (echo "logosSdk not found" && exit 1)
    test -d "${toString common.env.LOGOS_LIBLOGOS_ROOT}" || (echo "logosLiblogos not found" && exit 1)
    
    cmake -S . -B build \
      -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
      -DLOGOS_CPP_SDK_ROOT=$(pwd)/logos-cpp-sdk \
      -DLOGOS_LIBLOGOS_ROOT=${toString common.env.LOGOS_LIBLOGOS_ROOT}
    
    runHook postConfigure
  '';
  
  buildPhase = ''
    runHook preBuild
    
    cmake --build build
    echo "logos-package-manager-ui built successfully!"
    
    runHook postBuild
  '';
  
  installPhase = ''
    runHook preInstall
    
    mkdir -p $out/lib
    # Find and copy the built library file
    if [ -f "build/package_manager_ui.dylib" ]; then
      cp build/package_manager_ui.dylib $out/lib/
    elif [ -f "build/package_manager_ui.so" ]; then
      cp build/package_manager_ui.so $out/lib/
    else
      echo "Error: No library file found"
      exit 1
    fi
    
    
    runHook postInstall
  '';
}
